#!/usr/bin/env python3
"""Export FC1+GELU as board-qualified 64-channel CTC PWL kernels.

Depth Anything's ViT-S FC1 has 1536 outputs. A standalone PiecewiseActFun is
not code-generated by this DS toolchain and HighResLut hangs on the deployed
U250. Re-expressing each FC1 slice as a 1x1 Conv lets the compiler fuse the
weighted operation and calibrated eight-segment GELU into ``Conv2DPWL``.
"""

from __future__ import annotations

import argparse
import copy
import json
import math
from pathlib import Path

import numpy as np
import onnx
from onnx import TensorProto, helper, numpy_helper


TOKENS = 1370
INPUT_CHANNELS = 384
OUTPUT_CHANNELS = 1536
CHANNEL_SLICE = 64


def gelu(value: np.ndarray) -> np.ndarray:
    x = np.asarray(value, dtype=np.float64)
    z = x / math.sqrt(2.0)
    sign = np.sign(z)
    absolute = np.abs(z)
    t = 1.0 / (1.0 + 0.3275911 * absolute)
    polynomial = (((((1.061405429 * t - 1.453152027) * t)
                    + 1.421413741) * t - 0.284496736) * t + 0.254829592) * t
    erf = sign * (1.0 - polynomial * np.exp(-(absolute * absolute)))
    return 0.5 * x * (1.0 + erf)


def fit_pwl8(radius: float) -> dict:
    radius = max(float(radius), 3.001)
    points = np.asarray(
        [-radius, -3.0, -1.5, -0.75, 0.0, 0.75, 1.5, 3.0, radius],
        dtype=np.float64,
    )
    values = gelu(points)
    slopes = np.diff(values) / np.diff(points)
    intercepts = values[:-1] - slopes * points[:-1]
    slope_scale, intercept_scale = 64.0, 256.0
    slopes = np.clip(np.rint(slopes * slope_scale), -128, 127) / slope_scale
    intercepts = np.clip(np.rint(intercepts * intercept_scale), -128, 127) / intercept_scale
    sample = np.linspace(-radius, radius, 200001, dtype=np.float64)
    approximation = slopes[0] * sample + intercepts[0]
    for index in range(1, 8):
        approximation = np.where(
            sample > points[index],
            slopes[index] * sample + intercepts[index],
            approximation,
        )
    reference = gelu(sample)
    delta = approximation - reference
    return {
        "points": points.astype(np.float32).tolist(),
        "slopes": slopes.astype(np.float32).tolist(),
        "intercepts": intercepts.astype(np.float32).tolist(),
        "slope_scale": slope_scale,
        "intercept_scale": intercept_scale,
        "fit_rmse": float(np.sqrt(np.mean(delta * delta))),
        "fit_max_abs_error": float(np.max(np.abs(delta))),
        "fit_cosine": float(np.dot(approximation, reference) / (
            np.linalg.norm(approximation) * np.linalg.norm(reference)
        )),
    }


def fit_pwl8_samples(samples: np.ndarray, radius: float) -> dict:
    """Fit each hardware segment to the observed activation distribution."""
    radius = max(float(radius), 3.001)
    points = np.asarray(
        [-radius, -3.0, -1.5, -0.75, 0.0, 0.75, 1.5, 3.0, radius],
        dtype=np.float64,
    )
    x = np.asarray(samples, dtype=np.float64).reshape(-1)
    y = gelu(x)
    fallback = fit_pwl8(radius)
    slopes = []
    intercepts = []
    for index in range(8):
        lower = -np.inf if index == 0 else points[index]
        upper = np.inf if index == 7 else points[index + 1]
        mask = (x >= lower) & (x < upper)
        if np.count_nonzero(mask) < 2:
            slopes.append(fallback["slopes"][index])
            intercepts.append(fallback["intercepts"][index])
            continue
        design = np.stack((x[mask], np.ones(np.count_nonzero(mask))), axis=1)
        slope, intercept = np.linalg.lstsq(design, y[mask], rcond=None)[0]
        slopes.append(slope)
        intercepts.append(intercept)
    slope_scale, intercept_scale = 64.0, 256.0
    slopes = np.clip(np.rint(np.asarray(slopes) * slope_scale),
                     -128, 127) / slope_scale
    intercepts = np.clip(np.rint(np.asarray(intercepts) * intercept_scale),
                         -128, 127) / intercept_scale
    approximation = slopes[0] * x + intercepts[0]
    for index in range(1, 8):
        approximation = np.where(
            x > points[index],
            slopes[index] * x + intercepts[index],
            approximation,
        )
    delta = approximation - y
    return {
        "points": points.astype(np.float32).tolist(),
        "slopes": slopes.astype(np.float32).tolist(),
        "intercepts": intercepts.astype(np.float32).tolist(),
        "slope_scale": slope_scale,
        "intercept_scale": intercept_scale,
        "fit_rmse": float(np.sqrt(np.mean(delta * delta))),
        "fit_max_abs_error": float(np.max(np.abs(delta))),
        "fit_mean_error": float(np.mean(delta)),
        "fit_cosine": float(np.dot(approximation, y) / (
            np.linalg.norm(approximation) * np.linalg.norm(y)
        )),
    }


def attribute(node: onnx.NodeProto, name: str):
    return helper.get_attribute_value(next(item for item in node.attribute
                                           if item.name == name))


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--model", type=Path, required=True)
    parser.add_argument("--scale-profile", type=Path, required=True)
    parser.add_argument("--encoder-trace", type=Path, required=True,
                        help="hybrid U250 NPZ containing post_l00..post_l11")
    parser.add_argument("--encoder-tail-manifest", type=Path,
                        help="authoritative board-qualified FC1/FC2 input steps")
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--layers", type=int, nargs="*", default=list(range(12)))
    parser.add_argument("--carrier", choices=("conv", "matmul"), default="conv",
                        help="weighted instruction that carries the fused PWL")
    parser.add_argument("--pwl-fit", choices=("uniform", "activation-lsq"),
                        default="uniform")
    args = parser.parse_args()

    source = onnx.load(str(args.model), load_external_data=True)
    nodes = {node.name: node for node in source.graph.node}
    initializers = {item.name: numpy_helper.to_array(item)
                    for item in source.graph.initializer}
    profile = json.loads(args.scale_profile.read_text())
    tail = (json.loads(args.encoder_tail_manifest.read_text())
            if args.encoder_tail_manifest is not None else None)
    tail_by_layer = ({item["layer"]: item for item in tail["layers"]}
                     if tail is not None else {})
    trace = np.load(args.encoder_trace, allow_pickle=False)
    args.output_dir.mkdir(parents=True, exist_ok=True)
    records = []
    for layer in args.layers:
        prefix = f"/blocks.{layer}/mlp/fc1"
        matmul = nodes[prefix + "/MatMul"]
        add = nodes[prefix + "/Add"]
        weight = initializers[matmul.input[1]]
        bias = initializers[next(name for name in add.input if name in initializers)]
        if weight.shape != (INPUT_CHANNELS, OUTPUT_CHANNELS):
            raise ValueError(f"layer {layer}: unexpected FC1 weight {weight.shape}")
        if bias.shape != (OUTPUT_CHANNELS,):
            raise ValueError(f"layer {layer}: unexpected FC1 bias {bias.shape}")
        weight_steps = np.asarray(attribute(matmul, "B_scales"), np.float32)
        input_step = float(
            tail_by_layer[layer]["mlp"]["fc1_input_scale"]
            if tail is not None else profile["tensors"][
                f"/blocks.{layer}/norm2/LayerNormalization_output_0"
            ]["a8_scale"]
        )
        activation_stats = profile["tensors"][
            f"/blocks.{layer}/mlp/act/Mul_1_output_0"
        ]
        gelu_step = float(
            tail_by_layer[layer]["mlp"]["fc2_input_scale"]
            if tail is not None else activation_stats["a8_scale"]
        )
        norm = nodes[f"/blocks.{layer}/norm2/LayerNormalization"]
        gamma = initializers[norm.input[1]]
        beta = initializers[norm.input[2]]
        epsilon = float(attribute(norm, "epsilon"))
        post = np.asarray(trace[f"post_l{layer:02d}"], np.float32).reshape(
            TOKENS, INPUT_CHANNELS
        )
        mean = np.mean(post, axis=1, keepdims=True, dtype=np.float32)
        variance = np.mean((post - mean) ** 2, axis=1,
                           keepdims=True, dtype=np.float32)
        normalized = ((post - mean) / np.sqrt(variance + epsilon)
                      * gamma + beta).astype(np.float32)
        pre_gelu = normalized @ weight + bias
        pre_abs = np.abs(pre_gelu).reshape(-1)
        pre_abs_p9999 = float(np.percentile(pre_abs, 99.99))
        pre_gelu_step = pre_abs_p9999 / 127.0
        pre_saturation_percent = float(
            np.mean(np.abs(np.rint(pre_gelu / pre_gelu_step)) > 127.0) * 100.0
        )
        fit = (fit_pwl8_samples(pre_gelu, pre_abs_p9999)
               if args.pwl_fit == "activation-lsq"
               else fit_pwl8(pre_abs_p9999))

        for chunk, begin in enumerate(range(0, OUTPUT_CHANNELS, CHANNEL_SLICE)):
            end = begin + CHANNEL_SLICE
            name = f"mlp_fc1_gelu_l{layer:02d}_c{chunk:02d}"
            weight_name = name + ".weight"
            bias_name = name + ".bias"
            if args.carrier == "conv":
                weighted_nodes = [helper.make_node(
                    "Conv", ["input0", weight_name, bias_name], ["pre_gelu"],
                    name="/FC1_Conv1x1", kernel_shape=[1, 1], strides=[1, 1],
                    pads=[0, 0, 0, 0], dilations=[1, 1], group=1,
                    input_bitdepth=8, input_scale=1.0 / input_step,
                    input_scales=[input_step], weight_bitdepth=8,
                    weight_ch_scales=weight_steps[begin:end].tolist(),
                    output_bitdepth=8, output_scale=1.0 / pre_gelu_step,
                    output_scales=[pre_gelu_step],
                )]
                input_shape = [1, INPUT_CHANNELS, 1, TOKENS]
                output_shape = [1, CHANNEL_SLICE, 1, TOKENS]
                stored_weight = weight[:, begin:end].T[:, :, None, None]
            else:
                weighted_nodes = [
                    helper.make_node(
                        "MatMul", ["input0", weight_name], ["matmul"],
                        name="/FC1_MatMul", A_bitdepth=8,
                        A_scales=[input_step], B_bitdepth=8,
                        B_scales=weight_steps[begin:end].tolist(),
                        B_quant_dim=[1], output_bitdepth=16,
                        output_scale=-1.0,
                    ),
                    helper.make_node(
                        "Add", [bias_name, "matmul"], ["pre_gelu"],
                        name="/FC1_Add", const_bitdepth=16, const_scale=-1.0,
                        output_bitdepth=8, output_scale=1.0 / pre_gelu_step,
                        output_scales=[pre_gelu_step],
                    ),
                ]
                input_shape = [1, TOKENS, INPUT_CHANNELS]
                output_shape = [1, TOKENS, CHANNEL_SLICE]
                stored_weight = weight[:, begin:end]
            pwl = helper.make_node(
                "HardSwish", ["pre_gelu"], ["output0"], name="/GELU_PWL8",
                input_bitdepth=8, input_scale=1.0 / pre_gelu_step,
                input_scales=[pre_gelu_step], output_bitdepth=8,
                output_scale=1.0 / gelu_step, output_scales=[gelu_step],
                slopes=fit["slopes"], intercepts=fit["intercepts"],
                change_pts=fit["points"], slopes_scale=fit["slope_scale"],
                intercepts_scale=fit["intercept_scale"],
            )
            graph = helper.make_graph(
                [*weighted_nodes, pwl], name,
                [helper.make_tensor_value_info(
                    "input0", TensorProto.FLOAT, input_shape
                )],
                [helper.make_tensor_value_info(
                    "output0", TensorProto.FLOAT, output_shape
                )],
                [
                    numpy_helper.from_array(
                        np.ascontiguousarray(stored_weight),
                        weight_name,
                    ),
                    numpy_helper.from_array(np.ascontiguousarray(bias[begin:end]), bias_name),
                ],
            )
            model = helper.make_model(
                graph, opset_imports=copy.deepcopy(source.opset_import),
                producer_name="depthanything-u250-fc1-gelu-pwl",
            )
            model.ir_version = source.ir_version
            path = args.output_dir / f"{name}.onnx"
            onnx.save(model, str(path))
            records.append({
                "layer": layer, "chunk": chunk, "channel_start": begin,
                "channel_end": end, "name": name, "onnx": path.name,
                "input_shape": input_shape,
                "output_shape": output_shape,
                "input_step": input_step, "pre_gelu_step": pre_gelu_step,
                "output_step": gelu_step,
                "pre_gelu_abs_p9999": pre_abs_p9999,
                "pre_gelu_saturation_percent": pre_saturation_percent,
                "input_encoding": "INT8", "output_encoding": "INT8",
                "carrier": args.carrier,
                "lowering": ("Conv1x1+HardSwish -> acmosa.Conv2DPWL"
                             if args.carrier == "conv" else
                             "MatMul+Add+HardSwish -> compound MatMul PWL"),
                "pwl": fit,
            })

    manifest = {
        "schema_version": 1,
        "source_model": str(args.model.resolve()),
        "scale_profile": str(args.scale_profile.resolve()),
        "encoder_trace": str(args.encoder_trace.resolve()),
        "encoder_tail_manifest": (str(args.encoder_tail_manifest.resolve())
                                  if args.encoder_tail_manifest is not None else None),
        "strategy": f"24x64 FC1+INT8 {args.carrier} carrier PWL8 per layer; never HighResLut BF16",
        "carrier": args.carrier,
        "pwl_fit": args.pwl_fit,
        "logical_channels": OUTPUT_CHANNELS,
        "channel_slice": CHANNEL_SLICE,
        "calls_per_layer": OUTPUT_CHANNELS // CHANNEL_SLICE,
        "kernels": records,
    }
    manifest_path = args.output_dir / "manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n")
    print(manifest_path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
